version: '3.8'
services:
  # MySQL Database Service
  db:
    image: mysql:8.0.35
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: leaz_db
      MYSQL_ROOT_PASSWORD: your_strong_password # Change this if you want
    ports:
      - "3306:3306"
    volumes:
      - leaz_db_data:/var/lib/mysql

  # Spring Boot Application Service
  app:
    build: .
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # FIX: Added allowPublicKeyRetrieval=true to the database URL
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/leaz_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: your_strong_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  leaz_db_data:
